### ISSUE TITLE
Incorrect `mizani` and other version pins

### ISSUE THREAD

**Issue by krassowski** [conda-forge/plotnine-feedstock#40]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/conda-forge/plotnine-feedstock/blob/4da00e10d4ea05dacd8a8056a7d29555f93bef48/recipe/meta.yaml#L27-L34

Compare with upstream:

```
dependencies = [
    "matplotlib>=3.7.0",
    "pandas>=2.2.0",
    "mizani~=0.12.0",
    "numpy>=1.23.5",
    "scipy>=1.7.0",
    "statsmodels>=0.14.0",
]
```

https://github.com/has2k1/plotnine/blob/4159f9548fa5f95c02366efc324e88f9ba79af09/pyproject.toml#L24-L31

This means that latest `mizani` and latest `plotnine` cannot be installed together.

### Installed packages

```shell
Not relevant
```

### Environment info

```shell
Not relevant
```

**Comment by has2k1** [comment]
It should be the upstream dependencies for [v0.13.6](https://github.com/has2k1/plotnine/blob/v0.13.6/pyproject.toml#L25-L32), which are.

```toml
dependencies = [
    "matplotlib>=3.7.0",
    "pandas>=2.1.0,<3.0.0",
    "mizani~=0.11.0",
    "numpy>=1.23.0",
    "scipy>=1.7.0",
    "statsmodels>=0.14.0",
]
```

**Comment by krassowski** [comment]
Oh, right. I guess conda need to downgrade numpy in the meantime to continue using plotnine? Alluding to fix for https://github.com/has2k1/mizani/releases/tag/v0.12.2
